### ISSUE TITLE
Output file data_checking.txt not up-to-date

### ISSUE THREAD

**Issue by lutzilutz** [lutzilutz/TraficCERN#39]
Since we've implemented the Python script (computing data from the official entrance/exit data) directly in Java, the output is only composed of '0'.

**Comment by lutzilutz** [comment]
I think the old file data_checking.txt (created when you use sliders) is now just the data_enter_exit.txt file (created by our algorithm computing the probability matrix). Could you confirm @PavlosTserevelakis ?

**Comment by PavlosTserevelakis** [comment]
Agreed.

**Comment by lutzilutz** [comment]
Fixed in 7da6c8e862747aa9787ac59b80668495ea6cd8be. There is no need to check these values.
